/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.BilsemEtkinlik.GUI;

import com.BilsemEtkinlik.DAO.*;
import com.BilsemEtkinlik.Entity.*;
import com.BilsemEtkinlik.Is.*;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author serkancam
 */
public class OgrenciEkle extends javax.swing.JFrame {
    int secilenProgram=-1,secilenSinif=-1;

    /**
     * Creates new form OgrenciEkle
     */
    public OgrenciEkle() {
        initComponents();
    }
     void ProgramlarCbDoldur()
    {
     
       List<Programlar> programlar =null;
       Programlar pr=new Programlar();
       ProgramlarDAO islem=new ProgramlarDAO();
       programlar=islem.TumProgramlarGetir();
      
        for (Programlar prg : programlar) 
        {
            
           // Cift c=;
            cbProgramlar.addItem(new Cift2(prg.getProgramId(),prg.getProgramAdi()));          
            
        }
        
    }
     
     void SiniflarCbDoldur()
    {
     
       List<Siniflar> siniflar =null;
        SiniflarDAO islem=new SiniflarDAO();
            
       siniflar=islem.ProgramIdyeGoreGetir(secilenProgram);
       
       for (Siniflar sinif : siniflar) 
        {
            
           cbSiniflar.addItem(new Cift2(sinif.getSinifId(),sinif.getSinifKodu()));
            
            
        }
       
        
    }
     void OgrencilerTablosuDoldur()
     {
       
        List<Ogrenciler> ogrenciler=null;
        OgrencilerDAO ogrenciISlem=new OgrencilerDAO();
        ogrenciler=ogrenciISlem.SinifinOgrencileriniGetir(secilenSinif);
        DefaultTableModel model= (DefaultTableModel) tblOgrenciler.getModel();
        if(ogrenciler.size()>0)
        for(Ogrenciler ogrenci:ogrenciler)
        {
            model.addRow(new Object[]{false,ogrenci.getOgrenciNo(),ogrenci.getOgrenciAdi(),ogrenci.getOgrenciSoyadi()});
        }
        else
        {
            for(int i=0;i<8;i++)
            {model.addRow(new Object[]{false,-1,"",""});}
            
                      
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOgrenciler = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbProgramlar = new javax.swing.JComboBox<>();
        cbSiniflar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSinifKodu = new javax.swing.JTextField();
        btnSinifEkle = new javax.swing.JButton();
        lblBilgi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnOgrencileriGuncelle = new javax.swing.JButton();
        lblOgrenciBilgisi = new javax.swing.JLabel();
        btnOgrencileriSil = new javax.swing.JButton();
        btnOgrenciEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOgrenciler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seç", "Öğrenci No", "Öğrenci Adı", "Öğrenci Soyadı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblOgrenciler.setToolTipText("Yeni boş satır için enter'a basınız");
        tblOgrenciler.setShowHorizontalLines(true);
        tblOgrenciler.setShowVerticalLines(true);
        tblOgrenciler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblOgrencilerKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblOgrenciler);
        if (tblOgrenciler.getColumnModel().getColumnCount() > 0) {
            tblOgrenciler.getColumnModel().getColumn(0).setResizable(false);
            tblOgrenciler.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblOgrenciler.getColumnModel().getColumn(1).setResizable(false);
            tblOgrenciler.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblOgrenciler.getColumnModel().getColumn(2).setResizable(false);
            tblOgrenciler.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblOgrenciler.getColumnModel().getColumn(3).setResizable(false);
            tblOgrenciler.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 171, 680, 230));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbProgramlar.setModel(new javax.swing.DefaultComboBoxModel<>(new Cift2[] { new Cift2(-1,"Program Seç")}));
        cbProgramlar.setPreferredSize(new java.awt.Dimension(60, 30));
        cbProgramlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProgramlarActionPerformed(evt);
            }
        });
        jPanel1.add(cbProgramlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 166, 30));

        cbSiniflar.setModel(new javax.swing.DefaultComboBoxModel<>(new Cift2[] { new Cift2(-1,"Sınıf Seç")}));
        cbSiniflar.setPreferredSize(new java.awt.Dimension(56, 30));
        cbSiniflar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSiniflarActionPerformed(evt);
            }
        });
        jPanel1.add(cbSiniflar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 29, 166, 30));

        jLabel1.setText("Program Seç");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Sınıf Seç");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setText("<html>Eklenecek sınıf Kodu</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 70, 42));
        jPanel1.add(txtSinifKodu, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 77, 100, 30));

        btnSinifEkle.setText("<html>Seçilen Programa Sınıf Ekle</html>");
        btnSinifEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinifEkleActionPerformed(evt);
            }
        });
        jPanel1.add(btnSinifEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, 40));

        lblBilgi.setBackground(new java.awt.Color(204, 255, 255));
        lblBilgi.setText("İşlem Bilgisi");
        lblBilgi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBilgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 70, 158, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 380, 170));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 170));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOgrencileriGuncelle.setText("<html>Seçilen Öğrencileri Güncelle</html>");
        btnOgrencileriGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrencileriGuncelleActionPerformed(evt);
            }
        });
        jPanel2.add(btnOgrencileriGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        lblOgrenciBilgisi.setText("İşlem Bilgisi:");
        lblOgrenciBilgisi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblOgrenciBilgisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 30));

        btnOgrencileriSil.setText("<html>Seçilen Öğrencileri Sil</html>");
        btnOgrencileriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrencileriSilActionPerformed(evt);
            }
        });
        jPanel2.add(btnOgrencileriSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));

        btnOgrenciEkle.setText("Yeni Öğrencileri Ekle");
        jPanel2.add(btnOgrenciEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        ProgramlarCbDoldur();
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void cbProgramlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramlarActionPerformed
        // TODO add your handling code here:
        cbSiniflar.removeAllItems();
        cbSiniflar.addItem(new Cift2(-1,"Sınıf Seç"));
        secilenProgram=-1;
       if(cbProgramlar.getSelectedIndex()>0)
       {
        secilenProgram=((Cift2)cbProgramlar.getSelectedItem()).key;
        SiniflarCbDoldur();
       }
        
    }//GEN-LAST:event_cbProgramlarActionPerformed

    private void cbSiniflarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSiniflarActionPerformed
        // TODO add your handling code here:
        TabloIslemleri.TabloTemizle(tblOgrenciler);
        //DefaultTableModel model= (DefaultTableModel) tblOgrenciler.getModel();
        //model.addRow(new Object[]{false,null,"",""});
       
        secilenSinif=-1;
       if(cbSiniflar.getSelectedIndex()>0)
       {
        secilenSinif=((Cift2)cbSiniflar.getSelectedItem()).key;
        OgrencilerTablosuDoldur();
       }
        
    }//GEN-LAST:event_cbSiniflarActionPerformed

    private void btnSinifEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinifEkleActionPerformed
        // TODO add your handling code here:
        
        if(secilenProgram<0 && txtSinifKodu.getText().length()<3) 
        {
            lblBilgi.setText("<html>İlk önce program seçiniz veya uygun bir sınıf kodu giriniz.</html>");
            return;
        }    
        Programlar program= new Programlar();
        program.setProgramId(secilenProgram);
        Siniflar sinif =new Siniflar();
        sinif.setProgram(program);
        sinif.setSinifKodu(txtSinifKodu.getText());
        SiniflarDAO islem=new SiniflarDAO();
        if(islem.SinifEkle(sinif)>0)
        {
            lblBilgi.setText("<html>Sınıf Ekleme işlemi yapıldı</html>");
            cbProgramlar.setSelectedIndex(0);
        }
        
            
        
        
        
    }//GEN-LAST:event_btnSinifEkleActionPerformed

    private void tblOgrencilerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblOgrencilerKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
            DefaultTableModel model= (DefaultTableModel) tblOgrenciler.getModel();
            model.addRow(new Object[]{false,-1," "," "});
            
           
            
        }
    }//GEN-LAST:event_tblOgrencilerKeyPressed

    private void btnOgrencileriGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrencileriGuncelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOgrencileriGuncelleActionPerformed

    private void btnOgrencileriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrencileriSilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOgrencileriSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OgrenciEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOgrenciEkle;
    private javax.swing.JButton btnOgrencileriGuncelle;
    private javax.swing.JButton btnOgrencileriSil;
    private javax.swing.JButton btnSinifEkle;
    private javax.swing.JComboBox<Cift2> cbProgramlar;
    private javax.swing.JComboBox<Cift2> cbSiniflar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBilgi;
    private javax.swing.JLabel lblOgrenciBilgisi;
    private javax.swing.JTable tblOgrenciler;
    private javax.swing.JTextField txtSinifKodu;
    // End of variables declaration//GEN-END:variables
}
